from __future__ import annotations

from pathlib import Path
from .config import AppConfig
from .schema import IterationRecord
from .utils import ensure_dir


class ReportWriter:
    def __init__(self, config: AppConfig, run_id: str):
        self.config = config
        self.run_id = run_id
        self.run_dir = ensure_dir(Path(config.reports.output_dir) / run_id)

    def write_iteration(self, record: IterationRecord) -> Path:
        path = self.run_dir / f"iteration_{record.iteration:03d}.md"
        path.write_text(self._iteration_markdown(record), encoding="utf-8")
        self.write_iteration_transcript(record)
        return path

    def write_iteration_transcript(self, record: IterationRecord) -> Path:
        path = self.run_dir / f"discussion_{record.iteration:03d}.md"
        path.write_text(self._iteration_transcript_markdown(record), encoding="utf-8")
        return path

    def write_discussion_transcript(self, records: list[IterationRecord]) -> Path:
        path = self.run_dir / "discussion_transcript.md"
        lines = [
            f"# Visible Multi-Agent Discussion Transcript — {self.run_id}",
            "",
            "This file exposes the explicit agent outputs generated by the system. It is not a hidden chain of thought; it is a structured research transcript assembled from saved agent messages.",
            "",
        ]
        for record in records:
            lines.append(f"## Iteration {record.iteration}: {record.input_topic}")
            lines.append("")
            lines.append(
                f"See also: [full iteration report](iteration_{record.iteration:03d}.md) "
                f"and [iteration transcript](discussion_{record.iteration:03d}.md)."
            )
            lines.append("")
            lines.append(self._iteration_transcript_body(record))
            lines.append("\n---\n")
        path.write_text("\n".join(lines), encoding="utf-8")
        return path

    def write_final(self, records: list[IterationRecord]) -> Path:
        path = self.run_dir / "final_report.md"
        lines = [
            f"# Curiosity AI Final Report — {self.run_id}",
            "",
            f"Total iterations: {len(records)}",
            "",
            "## Trajectory",
            "",
        ]
        for r in records:
            score = r.curiosity_score.total if r.curiosity_score else 0.0
            title = r.synthesis.title if r.synthesis else "Untitled"
            gate = r.source_gate.decision if r.source_gate else "unknown"
            lines.append(f"### Iteration {r.iteration}: {title}")
            lines.append(f"- Input topic: {r.input_topic}")
            lines.append(f"- Source gate: {gate}")
            lines.append(f"- Curiosity score: {score:.3f}")
            if r.philosophical_depth:
                lines.append(f"- Philosophical depth score: {r.philosophical_depth.final_score:.3f} ({r.philosophical_depth.verdict})")
            if r.philosophical_move:
                lines.append(f"- Philosophical move: {r.philosophical_move.move_type} — {r.philosophical_move.final_quality_score:.3f} ({r.philosophical_move.verdict})")
            if r.strong_position:
                lines.append(f"- Strong position: {r.strong_position.thesis}")
            if r.curiosity_theory_state:
                lines.append(f"- Curiosity theory update: {r.curiosity_theory_state.new_property_this_iteration or r.curiosity_theory_state.latest_update}")
            lines.append(f"- Next topic: {r.next_topic or 'None'}")
            if r.synthesis:
                lines.append(f"- Thesis: {r.synthesis.thesis}")
            lines.append("")
        lines.append("## Full Iteration Reports")
        lines.append("")
        for r in records:
            lines.append(
                f"- [Iteration {r.iteration:03d}](iteration_{r.iteration:03d}.md) — "
                f"[agent transcript](discussion_{r.iteration:03d}.md)"
            )
        lines.append("")
        lines.append("## Visible Debate")
        lines.append("")
        lines.append("- [Full multi-agent discussion transcript](discussion_transcript.md)")
        self.write_discussion_transcript(records)
        path.write_text("\n".join(lines), encoding="utf-8")
        return path

    def _iteration_transcript_markdown(self, record: IterationRecord) -> str:
        return "\n".join(
            [
                f"# Discussion Transcript — Iteration {record.iteration}",
                "",
                f"**Run ID:** `{record.run_id}`",
                f"**Input topic:** {record.input_topic}",
                "",
                self._iteration_transcript_body(record),
            ]
        )

    def _iteration_transcript_body(self, record: IterationRecord) -> str:
        lines: list[str] = []

        lines += ["### Source Gate", ""]
        if record.source_gate:
            sg = record.source_gate
            lines += [
                f"**Decision:** {sg.decision}",
                f"**Primary sources:** {sg.primary_source_count}",
                f"**Memory sources:** {sg.memory_source_count}",
                f"**Web sources:** {sg.web_source_count}",
                f"**Reason:** {sg.reason}",
                "",
            ]
            if sg.missing_sources:
                lines.append("**Missing / needed sources:**")
                for m in sg.missing_sources:
                    lines.append(f"- {m}")
                lines.append("")
            if sg.usable_citations:
                lines.append("**Usable primary/web citations:**")
                for c in sg.usable_citations[:12]:
                    lines.append(f"- {c}")
                lines.append("")
        else:
            lines.append("No source gate recorded.\n")

        lines += [
            "### Reader / Grounding Agent",
            "",
            record.raw_agent_outputs.get("grounding_notes", "No grounding notes recorded.").strip(),
            "",
            "### Explorer Agent — Candidate Questions",
            "",
        ]
        if record.questions:
            for i, q in enumerate(record.questions, start=1):
                lines.append(f"**Q{i}. {q.question}**")
                if q.philosophical_tension:
                    lines.append(f"- Tension: {q.philosophical_tension}")
                if q.assumptions:
                    lines.append("- Assumptions: " + "; ".join(q.assumptions))
                if q.why_interesting:
                    lines.append(f"- Why interesting: {q.why_interesting}")
                if q.likely_sources:
                    lines.append("- Likely sources: " + "; ".join(q.likely_sources))
                if q.tags:
                    lines.append("- Tags: " + "; ".join(q.tags))
                lines.append("")
        else:
            lines.append("No candidate questions recorded.\n")

        lines += ["### Radical Question Agent — Aggressive Candidates", ""]
        if record.radical_candidates:
            for i, r in enumerate(record.radical_candidates, start=1):
                lines.append(f"**R{i}. {r.radical_question or r.radical_thesis}**")
                if r.radical_thesis:
                    lines.append(f"- Radical thesis: {r.radical_thesis}")
                if r.why_dangerous:
                    lines.append(f"- Why dangerous: {r.why_dangerous}")
                if r.required_sources:
                    lines.append("- Required sources: " + "; ".join(r.required_sources))
                if r.possible_objection:
                    lines.append(f"- Possible objection: {r.possible_objection}")
                lines.append("")
        else:
            lines.append("No radical candidates recorded.\n")

        lines += ["### Critic Agent — Filtering and Objections", ""]
        if record.critique:
            lines.append("**Accepted questions:**")
            if record.critique.accepted_questions:
                for q in record.critique.accepted_questions:
                    lines.append(f"- {q.question}")
            else:
                lines.append("- None recorded.")
            lines.append("")
            lines.append("**Rejected questions:**")
            if record.critique.rejected_questions:
                for item in record.critique.rejected_questions:
                    q = item.get("question") or "Unspecified question"
                    reason = item.get("reason") or "No reason given."
                    lines.append(f"- {q} — {reason}")
            else:
                lines.append("- None recorded.")
            lines.append("")
            lines.append("**Main objections:**")
            if record.critique.main_objections:
                for obj in record.critique.main_objections:
                    lines.append(f"- {obj}")
            else:
                lines.append("- None recorded. This means the critic needs stronger prompting or the model under-filled the field.")
            lines += [
                "",
                f"**Strongest question selected:** {record.critique.strongest_question or 'N/A'}",
                f"**Refinement:** {record.critique.refinement or 'N/A'}",
                "",
            ]
        else:
            lines.append("No critique recorded.\n")

        lines += [
            "### Research Agent — Source-Based Brief",
            "",
            record.raw_agent_outputs.get("research_brief", "No research brief recorded.").strip(),
            "",
        ]

        lines += ["### Textual Analyst Agent — Close Reading", ""]
        if record.textual_analyses:
            for a in record.textual_analyses:
                lines += [
                    f"#### {a.source_label or 'Unlabeled source'}",
                    f"- Source role: {a.source_role}",
                    f"- Literal claim: {a.literal_claim}",
                    f"- Key concepts: {', '.join(a.key_concepts) if a.key_concepts else 'N/A'}",
                    f"- Interpretation: {a.interpretive_analysis}",
                    f"- Relevance: {a.relevance_to_question}",
                    f"- Anachronism risk: {a.anachronism_risk}",
                    f"- Limitations: {a.limitations}",
                    "",
                ]
        else:
            lines.append("No textual analyses recorded.\n")

        if record.argument_reconstruction:
            ar = record.argument_reconstruction
            lines += [
                "### Argument Reconstructor Agent",
                "",
                f"**Central claim:** {ar.central_claim}",
                "",
                "**Premises:**",
            ]
            if ar.premises:
                for p in ar.premises:
                    lines.append(f"- {p}")
            else:
                lines.append("- None recorded.")
            lines += [
                "",
                f"**Conclusion:** {ar.conclusion}",
                "",
                "**Hidden assumptions:**",
            ]
            if ar.hidden_assumptions:
                for h in ar.hidden_assumptions:
                    lines.append(f"- {h}")
            else:
                lines.append("- None recorded.")
            lines.append("")
            lines.append("**Inferential gaps:**")
            if ar.inferential_gaps:
                for g in ar.inferential_gaps:
                    lines.append(f"- {g}")
            else:
                lines.append("- None recorded.")
            lines += [
                "",
                f"**Strongest objection:** {ar.strongest_objection}",
                f"**Possible reply:** {ar.possible_reply}",
                "",
            ]

        if record.strong_position:
            sp = record.strong_position
            lines += [
                "### Strong Position Enforcer",
                "",
                f"**Position type:** {sp.position_type}",
                f"**Thesis:** {sp.thesis}",
                f"**Decisive condition:** {sp.decisive_condition or 'N/A'}",
                f"**Defended claim:** {sp.defended_claim}",
                f"**Concession:** {sp.concession}",
                f"**Reasoning strategy:** {sp.reasoning_strategy}",
                "",
            ]
            if sp.source_labels:
                lines.append("**Source labels:**")
                for src in sp.source_labels:
                    lines.append(f"- {src}")
                lines.append("")

        if getattr(record, "balance_stress_test", None):
            bs = record.balance_stress_test
            lines += [
                "### Balance Stress Tester",
                "",
                f"**Balance claim detected:** {bs.balance_claim_detected}",
                f"**Verdict:** {bs.verdict}",
                f"**What is balanced:** {bs.what_is_balanced}",
                f"**Who/what decides balance:** {bs.who_or_what_decides_balance}",
                f"**Criterion for virtue:** {bs.criterion_for_virtue}",
                f"**Criterion for danger:** {bs.criterion_for_danger}",
                f"**Hard question for synthesis:** {bs.hard_question_for_synthesis}",
                "",
                "**Failure modes:**",
            ]
            for item in bs.failure_modes or ["None recorded."]:
                lines.append(f"- {item}")
            lines.append("")

        if record.curiosity_score:
            lines += [
                "### Curiosity Engine",
                "",
                f"Score: **{record.curiosity_score.total:.3f}**",
                "",
                record.curiosity_score.explanation,
                "",
            ]

        if record.synthesis:
            lines += [
                "### Synthesizer Agent — Deep Report",
                "",
                record.synthesis.report_markdown or record.synthesis.thesis,
                "",
            ]

        if record.argument_critique:
            ac = record.argument_critique
            lines += [
                "### Argument Critic Agent — Post-Synthesis Attack",
                "",
                f"**Verdict:** {ac.verdict}",
                "",
                "**Major objections:**",
            ]
            for item in ac.major_objections or ["None recorded."]:
                lines.append(f"- {item}")
            lines.append("")
            lines.append("**Citation problems:**")
            for item in ac.citation_problems or ["None recorded."]:
                lines.append(f"- {item}")
            lines.append("")
            lines.append("**Logical gaps:**")
            for item in ac.logical_gaps or ["None recorded."]:
                lines.append(f"- {item}")
            lines.append("")
            lines.append("**Anachronism warnings:**")
            for item in ac.anachronism_warnings or ["None recorded."]:
                lines.append(f"- {item}")
            lines.append("")
            lines.append("**Revision instructions:**")
            for item in ac.revision_instructions or ["None recorded."]:
                lines.append(f"- {item}")
            lines.append("")

        if record.philosophical_depth:
            pd = record.philosophical_depth
            lines += [
                "### Philosophical Depth Judge",
                "",
                f"**Final depth score:** {pd.final_score:.3f}",
                f"**Verdict:** {pd.verdict}",
                "",
                "**Dimension scores:**",
                f"- Concept definition: {pd.concept_definition:.2f}",
                f"- Anachronism control: {pd.anachronism_control:.2f}",
                f"- Genuine tension: {pd.genuine_tension:.2f}",
                f"- Counterargument strength: {pd.counterargument_strength:.2f}",
                f"- Source interpretation: {pd.source_interpretation:.2f}",
                f"- Curiosity theme progress: {pd.curiosity_theme_progress:.2f}",
                "",
                "**Main findings:**",
            ]
            for item in pd.main_findings or ["None recorded."]:
                lines.append(f"- {item}")
            lines.append("")
            lines.append("**Depth failures:**")
            for item in pd.depth_failures or ["None recorded."]:
                lines.append(f"- {item}")
            lines.append("")
            lines.append("**Required revisions:**")
            for item in pd.required_revisions or ["None recorded."]:
                lines.append(f"- {item}")
            if pd.curiosity_progress_note:
                lines.append("")
                lines.append(f"**Curiosity progress note:** {pd.curiosity_progress_note}")
            lines.append("")

        if record.philosophical_move:
            pm = record.philosophical_move
            lines += [
                "### Real Philosophical Move Detector",
                "",
                f"**Move type:** {pm.move_type}",
                f"**Quality score:** {pm.final_quality_score:.3f}",
                f"**Verdict:** {pm.verdict}",
                f"**Move statement:** {pm.move_statement}",
                f"**Concept definition:** {pm.concept_definition}",
                f"**Paradox / tension:** {pm.paradox_or_tension}",
                f"**Why this advances curiosity:** {pm.why_it_advances_curiosity}",
                f"**Hedge count:** {pm.hedge_count}",
                f"**Hedge penalty:** {pm.hedge_penalty:.3f}",
                f"**Unsupported inference penalty:** {pm.unsupported_inference_penalty:.3f}",
                f"**Required revision:** {pm.required_revision or 'None recorded.'}",
                "",
            ]
            if pm.source_support:
                lines.append("**Source support:**")
                for src in pm.source_support:
                    lines.append(f"- {src}")
                lines.append("")

        if record.curiosity_theory_state:
            cs = record.curiosity_theory_state
            lines += [
                "### Curiosity Theory State",
                "",
                f"**Current definition:** {cs.current_definition}",
                f"**New property this iteration:** {cs.new_property_this_iteration or 'None recorded.'}",
                f"**Latest update:** {cs.latest_update}",
                f"**Next required move:** {cs.next_required_move}",
                f"**Confidence:** {cs.confidence:.2f}",
                "",
                "**Properties discovered:**",
            ]
            for item in cs.properties_discovered or ["None recorded."]:
                lines.append(f"- {item}")
            lines.append("")
            lines.append("**Unresolved tensions:**")
            for item in cs.unresolved_tensions or ["None recorded."]:
                lines.append(f"- {item}")
            lines.append("")

        if record.evaluation:
            lines += [
                "### Evaluator Agent",
                "",
                f"Evaluator score: **{record.evaluation.score:.3f}**",
                f"Should publish after approval: **{record.evaluation.should_publish}**",
                f"Should continue: **{record.evaluation.should_continue}**",
                "",
                "**Strengths:**",
            ]
            for item in record.evaluation.strengths or ["None recorded."]:
                lines.append(f"- {item}")
            lines.append("")
            lines.append("**Weaknesses:**")
            for item in record.evaluation.weaknesses or ["None recorded."]:
                lines.append(f"- {item}")
            if record.evaluation.citation_issues:
                lines.append("")
                lines.append("**Citation issues:**")
                for item in record.evaluation.citation_issues:
                    lines.append(f"- {item}")
            if record.evaluation.recommended_revision:
                lines.append("")
                lines.append(f"**Recommended revision:** {record.evaluation.recommended_revision}")
            lines.append("")

        if record.planning:
            lines += [
                "### Planning Agent",
                "",
                f"Mode: **{record.planning.exploit_or_explore}**",
                f"Chosen next topic: **{record.planning.chosen_next_topic}**",
                f"Reason: {record.planning.reason}",
                "",
                "**Alternative topics:**",
            ]
            for item in record.planning.alternative_topics or ["None recorded."]:
                lines.append(f"- {item}")
            lines.append("")

        lines += ["### Sources Visible to Agents", ""]
        if record.retrieved_passages:
            for p in record.retrieved_passages:
                source = p.source
                lines.append(f"- {p.citation} — {source.author or 'Unknown'}, *{source.title}* ({source.source_type})")
        if record.web_results:
            for w in record.web_results:
                lines.append(f"- {w.citation} — {w.title}: {w.url}")
        if not record.retrieved_passages and not record.web_results:
            lines.append("- No retrieved sources recorded.")
        lines.append("")
        return "\n".join(lines)

    def _iteration_markdown(self, record: IterationRecord) -> str:
        lines = [
            f"# Iteration {record.iteration} — Curiosity Report",
            "",
            f"**Run ID:** `{record.run_id}`",
            f"**Created:** {record.created_at}",
            f"**Input topic:** {record.input_topic}",
            "",
            f"[Visible agent discussion for this iteration](discussion_{record.iteration:03d}.md)",
            "",
        ]
        if record.source_gate:
            lines += [
                "## Source Gate",
                "",
                f"**Decision:** {record.source_gate.decision}",
                f"**Reason:** {record.source_gate.reason}",
                "",
            ]
        if getattr(record, "balance_stress_test", None):
            bs = record.balance_stress_test
            lines += [
                "### Balance Stress Tester",
                "",
                f"**Balance claim detected:** {bs.balance_claim_detected}",
                f"**Verdict:** {bs.verdict}",
                f"**What is balanced:** {bs.what_is_balanced}",
                f"**Who/what decides balance:** {bs.who_or_what_decides_balance}",
                f"**Criterion for virtue:** {bs.criterion_for_virtue}",
                f"**Criterion for danger:** {bs.criterion_for_danger}",
                f"**Hard question for synthesis:** {bs.hard_question_for_synthesis}",
                "",
                "**Failure modes:**",
            ]
            for item in bs.failure_modes or ["None recorded."]:
                lines.append(f"- {item}")
            lines.append("")

        if record.curiosity_score:
            lines += [
                "## Curiosity Score",
                "",
                f"**Total:** {record.curiosity_score.total:.3f}",
                "",
                f"{record.curiosity_score.explanation}",
                "",
            ]
        if record.critique:
            lines += [
                "## Strongest Question",
                "",
                record.critique.strongest_question or "N/A",
                "",
                "## Strong Position",
                "",
                record.strong_position.thesis if record.strong_position else "N/A",
                "",
                "## Critic Notes",
                "",
            ]
            for obj in record.critique.main_objections:
                lines.append(f"- {obj}")
            if not record.critique.main_objections:
                lines.append("- None recorded.")
            lines.append("")
        if record.synthesis:
            lines += [
                "## Deep Synthesis",
                "",
                record.synthesis.report_markdown or record.synthesis.thesis,
                "",
                "## Next Directions",
                "",
            ]
            for d in record.synthesis.next_directions:
                lines.append(f"- {d}")
            lines.append("")
        if record.argument_critique:
            lines += [
                "## Argument Critique",
                "",
                f"**Verdict:** {record.argument_critique.verdict}",
                "",
            ]
            for obj in record.argument_critique.major_objections:
                lines.append(f"- {obj}")
            lines.append("")
        if record.philosophical_depth:
            pd = record.philosophical_depth
            lines += [
                "## Philosophical Depth Judgment",
                "",
                f"**Final score:** {pd.final_score:.3f}",
                f"**Verdict:** {pd.verdict}",
                "",
                "### Dimension Scores",
                "",
                f"- Concept definition: {pd.concept_definition:.2f}",
                f"- Anachronism control: {pd.anachronism_control:.2f}",
                f"- Genuine tension: {pd.genuine_tension:.2f}",
                f"- Counterargument strength: {pd.counterargument_strength:.2f}",
                f"- Source interpretation: {pd.source_interpretation:.2f}",
                f"- Curiosity theme progress: {pd.curiosity_theme_progress:.2f}",
                "",
                "### Depth Failures",
                "",
            ]
            for item in pd.depth_failures:
                lines.append(f"- {item}")
            if not pd.depth_failures:
                lines.append("- None recorded.")
            lines.append("")
            lines.append("### Required Revisions")
            lines.append("")
            for item in pd.required_revisions:
                lines.append(f"- {item}")
            if not pd.required_revisions:
                lines.append("- None recorded.")
            lines.append("")

        if record.philosophical_move:
            pm = record.philosophical_move
            lines += [
                "## Real Philosophical Move",
                "",
                f"**Type:** {pm.move_type}",
                f"**Score:** {pm.final_quality_score:.3f}",
                f"**Verdict:** {pm.verdict}",
                f"**Move:** {pm.move_statement}",
                f"**Why it advances curiosity:** {pm.why_it_advances_curiosity}",
                f"**Hedging penalty:** {pm.hedge_penalty:.3f}",
                "",
            ]
        if record.curiosity_theory_state:
            cs = record.curiosity_theory_state
            lines += [
                "## Curiosity Theory State",
                "",
                f"**Current definition:** {cs.current_definition}",
                f"**New property:** {cs.new_property_this_iteration or 'None recorded.'}",
                f"**Next required move:** {cs.next_required_move}",
                "",
            ]

        if record.evaluation:
            lines += [
                "## Evaluation",
                "",
                f"**Evaluator score:** {record.evaluation.score:.3f}",
                f"**Should publish after approval:** {record.evaluation.should_publish}",
                f"**Should continue:** {record.evaluation.should_continue}",
                "",
                "### Weaknesses",
                "",
            ]
            for w in record.evaluation.weaknesses:
                lines.append(f"- {w}")
            if not record.evaluation.weaknesses:
                lines.append("- None recorded.")
            if record.evaluation.citation_issues:
                lines.append("")
                lines.append("### Citation Issues")
                lines.append("")
                for c in record.evaluation.citation_issues:
                    lines.append(f"- {c}")
            lines.append("")
        if record.planning:
            lines += [
                "## Planning Decision",
                "",
                f"**Mode:** {record.planning.exploit_or_explore}",
                f"**Chosen next topic:** {record.planning.chosen_next_topic}",
                f"**Reason:** {record.planning.reason}",
                "",
                "### Alternatives",
                "",
            ]
            for t in record.planning.alternative_topics:
                lines.append(f"- {t}")
            lines.append("")
        lines += ["## Sources Retrieved", ""]
        for p in record.retrieved_passages:
            source = p.source
            lines.append(f"- {p.citation} — {source.author or 'Unknown'}, *{source.title}* ({source.source_type})")
        for w in record.web_results:
            lines.append(f"- {w.citation} — {w.title}: {w.url}")
        lines.append("")
        return "\n".join(lines)
